language: node_js
node_js:
- '12'
sudo: required
services:
- docker
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: u7OfJNewfKdcVaLAUdzB9LFSGy1AoXx5nhJA1eiiGwFUpqZwDxqyeo1SpVjnK6Gvk8I1HTDp6eFcZYdhM7s63i/CZplL7uzkVYupg9A72gDRf6Zdk8pDyhdPounfB+Ib1PdJ06JrzOqv2QkYKF04xhwW1AmgamY7s4By0A92jnKEB1Yh5WVQE0dW+uvrMaDFtrjiYQ06zu/xFCYyUD3FlznaBG+PGTo4PHfC6U6yW/wFLYsIBYmFDH/QK41h6p+7PQvFejC8rRBFTPyRSUlckw4PAUm80mBEj6ZuuE4WC/xgvxioomMiG/OQj8IfMuGLv9S01EweKj6X+cDXfcYVmy1mSzsqz6OwGh9KK0mG+Hme+Cch4DQ+WWHzMredFnz3rc52kIdf5fRNHRx2+y9XwjrOzgbxM4uz2y6P5/yo8FfuDnA3n6Ka3OWV4S7bUEF0xWkJ3IBlXeS7eoPAXLVMecLKKWPkNnY60zfIWjYh7I1t9bH4QTv9KbqvldtCY7auYLs3mEeR0bLwKcAi8YcycCqCMN6Krs98wetQI0CbiZFWZ7RyWBCR9zqaFx24v4JO2S2AJ84H5DOJyojI9Mk3eR0aJ/R/Oo2nx3B9dwBZhmfPaBcZLPij+IWxfgmMjs77yzOWPjmmf0RF1qzSOORltLY/xsU8bzwis9e4KdmUw0Y=
script:
- bash .travis.build.sh
