language: node_js
node_js:
- '12'
sudo: required
services:
- docker
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: cZGZNFsraHfr/06izLkNxZGi2m8LnDN7hdzZG90x1Lz4kLsuGA7yoQMHuS0f3/HjwZurGxxlhP6P8u+IrT2FuV52Lj+9oWRpdSGC65kbFCakINM21rQtJ0JMx8Oa/zzdJmiQ3GFs8Bo2NTGUgdB7dCh18ZYcAL1QYj1SNm4twBOZQP6KnvimXlbqYdaG34JqGfzkzU24xCVau2CvRKDF3VwHKlUqD6NtFBZidIlgZeCnWlfe1U1xLxS/ZwGqN20ZszSYjhDtTj6WNPEaqmmYwtq6Z4OzjgxJCRkbD7Q7SKpOZIObzNVs7ObKZBLP0+1EEmiXNX2uHMM+UDi0R0fubDE/k+92nEPAgHotI5BAkl5uzH2cD50HVKP18zbk7ETUnvAz59zM9Y0+BcifsE4ZlPJTuuZgNaLfhMTVTgM2ELpFwauQN9GS6kc4kKeW3dgz5yo4K495I0Xb6XbUTx8jlPTYXwLLpPhTVspJly+xOcZdvHDZ8AVP8jUbEgdN4I5KfRS7cEXeSAINR1mpaPSx3tof304aRtrnoK8OyyTDSVowCpILHABgwpiUPATDnZPlbFP/ajMYvn43yNFwatlXlLsEjC3qIIIe2mMcADWFBjtT1Xn0VyhTu/9uZTFQCDKbWOhXpZGFl4ovPR/YB67d1/tZe70RQZRjb5JApKF9aCg=
script:
- bash .travis.build.sh
