language: node_js
node_js:
- '12'
sudo: required
services:
- docker
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: n49czAHDd9tSkDNcLOo9TcaYQf9UZ/n2tpyNQQWH5MMh2jC6Z4NnomwhTcFc1xu7tWHHdgQwhM3EIsrMxZwXDZ15x/zsfeSyxkzO48FDG6uSpyv9mMcHH1XVG0HBzgg5d1f6I7Q0ZzM0bewN3yKGVcSCSqwPDms9i1SSFWMCjqf728UCl6w7fT3x4DFAkkybeSjkp5l7U8m0UTRiZF9jXKcCjADotG3twUY014GCX1RlXR3jHw2zsP4PaZrk2w4MN68LlMO9rPGr2XL/3RHA2iyEgizWHGGId95DDf4sMDNSm+1TQM2XgdlVpfvjHE8340ZVTJzHEnDJHZrJ/u+TQeeWVrJ1f7drczrQysvZE0yIVONYJ563JOcpcI8SVBmXFnFDIUZGW3jYLaSU4bIV+qr6iuiwkFlbCxXMEVu13JBOu5CHj4doa6aMxuXfytX7Der1a2rhNRUVqj3pTpPusqbtaS70Nen3JPn3lLBED1dyim+15NPOFllK+rjbgpZAqS2ogdgt4bB2ytzdZwlMLZvBKkWrgxhcoaP7ikzalFoC0vhrL20vJmmLDGKFV7JUJUhySrqv0ZIOjtBbpw7HiIId3tT5t7nsX5Dcp2a4ZsTfg+U7XaG8LcGxvXe5t29y5NprLROS0MUIwGpWdnW4SOwTCJT+aNBNvdpQ82ACJCI=
script:
- bash .travis.build.sh
