version: '3.3'

services:
  app:
    build: 
      context: .
    image: kalisio/kontrol
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - UNDER_TEST=1
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}